version: '3.8'

services:
  playwright:
    build: .
    environment:
      - BASE_URL=https://the-internet.herokuapp.com
      - HEADLESS=true
      - PLAYWRIGHT_HEADLESS=true
    command: mvn test -Dtest=CheckboxTest -Dplaywright.headless=true -e
    volumes:
      - ./screenshots:/app/screenshots
    shm_size: 2g