name: Docker Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'src/test/java/courseplaywtests/DynamicControlsTest.java'

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t playwright-junit-test .

      - name: Run tests
        run: |
          docker run --rm \
            --shm-size=2g \
            -e BASE_URL=https://the-internet.herokuapp.com \
            playwright-junit-test \
            mvn test -Dtest=DynamicControlsTest -e -X

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
          retention-days: 30
